StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{661B4EB8ADC91FDD}" {
   Id "TSE-Briefcase_black"
   Target_en_us "Black briefcase"
   Target_ru_ru "Чёрный дипломат"
   Modified 1713067242
   Author "Osi"
   LastChanged "Osi"
  }
  CustomStringTableItem "{661B4EB8AAA78D75}" {
   Id "TSE-Briefcase_black_locked"
   Target_en_us "Locked black briefcase"
   Target_ru_ru "Запертый чёрный дипломат"
   Modified 1713067287
   Author "Osi"
   LastChanged "Osi"
  }
  CustomStringTableItem "{661B4EB8AF0A244E}" {
   Id "TSE-Briefcase_brown"
   Target_en_us "Brown briefcase"
   Target_ru_ru "Коричневый дипломат"
   Modified 1713067244
   Author "Osi"
   LastChanged "Osi"
  }
  CustomStringTableItem "{661B4EB8A3EF713F}" {
   Id "TSE-Briefcase_brown_locked"
   Target_en_us "Locked brown briefcase"
   Target_ru_ru "Запертый коричневый дипломат"
   Modified 1713067257
   Author "Osi"
   LastChanged "Osi"
  }
  CustomStringTableItem "{661B4EB8C9BE76B4}" {
   Id "TSE-Briefcase_description"
   Target_en_us "An inconspicuous, small-capacity briefcase."
   Target_ru_ru "Неприметный, маловместительный дипломат."
   Modified 1713067607
   Author "Osi"
   LastChanged "Osi"
  }
  CustomStringTableItem "{661B4EB8D5E14551}" {
   Id "TSE-Briefcase_description_locked"
   Target_en_us "An inconspicuous locked briefcase. Could contain anything."
   Target_ru_ru "Неприметный запертый дипломат."
   Modified 1713067981
   Author "Osi"
   LastChanged "Osi"
  }
 }
}