StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6618F080380395E1}" {
   Id "TSE-Item_Lockpick"
   Target_en_us "Lockpick"
   Target_ru_ru "Отмычка"
   Modified 1712917910
   Author "Osi"
   LastChanged "Osi"
  }
  CustomStringTableItem "{6618F080286CCE66}" {
   Id "TSE-Item_Lockpick_Description"
   Target_en_us "Used to get access to locked vehicles"
   Target_ru_ru "Используюется для взлома закрытой техники"
   Modified 1712917944
   Author "Osi"
   LastChanged "Osi"
  }
 }
}